### ISSUE TITLE
Is it possible to use Immich app with Immich behind YNH basic auth?

### ISSUE THREAD

**Issue by CodeShakingSheep** [YunoHost-Apps/immich_ynh#124]
I just set up Immich on my server and was surprised that they don't provide 2FA out of the box, see https://github.com/immich-app/immich/discussions/8175.

So, as an alternative to 2FA I wanted to keep Immich running behind YNH basic auth. Support for using basic auth in the app has been implemented and merged according to https://github.com/immich-app/immich/pull/6840 . However, when I specify my YNH URL as server in the URL like this `https://YNH_USER:YNH_PASS@IMMICH_URL.com` and then try to login with my Immich user credentials it's not working.

After specifying the server URL I also receive the message `Your app major version is not compatible with the server!` although both my server and the app are running on version 1.117.0. I suppose this is because of the YNH auth which somehow cannot be passed.

So, my question is if anyone successfully got Immich setup with using YNH basic auth?

**Comment by MadMan247** [comment]
To try to sanity check, I attempted immich@user.email:immichPWD@sub.immich.com (no SSO required to access this instance of immich; publicly visible) and ynhuser:ynhpassword@sub.yunohost.tld 
I attempted this on both firefox and edge

I was neither able to log into the SSOwat nor Immich.

I tried using the mobile app too, but any more than a single @ in the URL caused it to say "invalid URL" and it refused to try to connect. (using multiple @'s because immich wants emails to sign in. Again, no SSO enabled here. The format at least redirected in the browser, so I know it would connect if the app let me try.)

My thoughts were that, if this is going to work, the ynhuser:ynhpassword@sub.yunohost.tld should log me in to YNH's SSO (or bypass it), but since this did not, I assume that it is not implemented in yunohost's side.

So either I am doing something entirely incorrectly, misunderstanding something, or it doesn't work. I will do a few more tests and report back.

**Comment by CodeShakingSheep** [comment]
Thanks for your insights @MadMan247 !

I could get this to work. First, I had to make Immich publicly available (no SSO). Then I had to create a `.htpasswd` file (also see https://forum.yunohost.org/t/protecting-some-applications-paths-with-http-basic-auth/23243). In my case it was important to use a plain password with no special chars, otherwise Immich mobile app wouldn't let me log in. Then I had to alter `/etc/nginx/conf.d/<IMMICH_DOMAIN>.d/immich.conf` by adding the following lines (directly under the first line `location / {`):

```
auth_basic "Please identify for Immich";
auth_basic_user_file /etc/nginx/conf.d/<IMMICH_DOMAIN>.d/.htpasswd;
```
After that I ran `nginx -t` to check that the config is ok and finally `systemctl reload nginx`. I could log in with Basic auth credentials set in `.htpasswd` both in the browser as well as in the mobile app. Hope this helps.
