### ISSUE TITLE
Bug: HEIC and HEIF Photos Broken

### ISSUE THREAD

**Issue by johnnyq** [YunoHost-Apps/immich_ynh#40]
HEIC and HEIF iPhone Photos are broken after upload to Immich using the Immich app

### Context

- Hardware: Debian 12 LXC VPS
- YunoHost Latest Stable

### Steps to reproduce

- Take Photos with an iPhone use the Immich App to upload them
- Login to the Web Interface and you get this
![image](https://github.com/YunoHost-Apps/immich_ynh/assets/1812594/557f14a2-339d-4090-b65b-58cbfe778f07)

jpg are fine hence the screenshot

### Expected behavior

HEIC and HEIF Photos should work

**Comment by ewilly** [comment]
Hi,
HEIC is a patented file format (Nokia licensing) and not compatible with LGPL License so sharp sharp does not include it by default.
Using libvips of debian could have been a solution...
...but as often with debian package, the available version does not fit minimal requirements versioning to use globally-installed version of libvips instead of the provided binaries (see [sharp - High performance Node.js image processing](https://sharp.pixelplumbing.com/install#custom-libvips))
The only way is keeping JPEG format on your iphone.

**Comment by Grindingstill** [comment]
Having the same issue with heic from iphone with image not showing up using yunohost immich

**Comment by RlndVt** [comment]
Hi,

> Using libvips of debian could have been a solution...
> ...but as often with debian package, the available version does not fit minimal requirements versioning to use globally-installed version of libvips instead of the provided binaries (see [sharp - High performance Node.js image processing](https://sharp.pixelplumbing.com/install#custom-libvips))

Am I correct that this would/could be fixed by having a newer version of libvips globally-installed? E.g. after upgrading to Trixie?
